fixtures:
  forge_modules:
    stdlib: 'puppetlabs/stdlib'
    archive: 'puppet/archive'
    concat: 'puppetlabs/concat'
    cron_core:
      repo: 'puppetlabs/cron_core'
      ref: '1.3.0'
    device_manager: 'puppetlabs/device_manager'
    extlib: 'puppet/extlib'
  symlinks:
    nexus: "#{source_dir}"
